#!/bin/bash

tag=$(./gradlew -q printVersionTag)

echo $tag
if [[ "$TRAVIS_BRANCH" == "$PROD_BRANCH" ]]; then
  if [[ "$tag" == *-SNAPSHOT ]]; then
    echo "Version format '${tag}' is not valid for production. Most probably SNAPSHOT prefix wasn't removed from version number."
    exit 1
  fi
  (git tag -l | grep -q "$tag") && {
    echo "Tag '${tag}' already exists in repository. Most probably this version was already deployed to production."
    exit 1
  }
fi

exit 0