name: pipeline

on:
  push:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assemble javadoc
      - name: Cache jar
        uses: actions/cache@v2
        with:
          path: build/libs
          key: jar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Get jar
        uses: actions/cache@v2
        with:
          path: build/libs
          key: jar
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test
        run: ./gradlew test -x classes -x jar

  test-with-java-8:
    if: ${{ github.event_name == 'pull_request' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Get jar
        uses: actions/cache@v2
        with:
          path: build/libs
          key: jar
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test
        run: ./gradlew test -x classes -x jar
  
  # add some other tests here

  generate-code-coverage:
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew jacocoTestReport
      - name: Publish coverage report
        uses: codecov/codecov-action@v2

  release:
    #if: startsWith(github.ref, 'refs/tags/')
    if: github.ref == 'refs/heads/main'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Get jar
        uses: actions/cache@v2
        with:
          path: build/libs
          key: jar
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish to Maven Central
        run: ./gradlew publishToSonatype closeSonatypeStagingRepository -x javadoc -x classes -x jar
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      # - name: Github release
      #   uses: softprops/action-gh-release@v1
